version: '3.7'
services:
  db:
    container_name: db
    image: postgres:latest
    platform: linux/amd64
    ports:
      - '5001:5432'
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    tty: true
